name: Cypress Tests
           on: [push]
            jobs:
               Cypress-Test:
                  runs-on: ubuntu-latest
                   steps:
                         - name: Checkout GitCode
                           uses: actions/checkout@v2
                           run: |
                             mix deps.get
                             mix compile
 
                         - name: Run Cypress Test
                           uses: cypress-io/github-action@v4
                     with:
                           build: npm run build --prefix assets
                           start: mix phx.server
